### ISSUE TITLE
I'm getting again and again the same "Go linter running error", why?

### ISSUE THREAD

**Issue by frederikhors** [xxpxxxxp/intellij-plugin-golangci-lint#100]
I'm getting again and again the same error in Goland:

```
Go linter running error
Please make sure there's no syntax error, then check if any config error
```

I have the below `.golangci-lint.yml` file in my root dir:

```yml
linters:
  enable-all: true
  disable:
    - dupl
    - exhaustivestruct
    - gci
    - gochecknoinits
    - godox
    - gofmt
    - gofumpt
    - goimports
    - golint # deprecated
    - gomnd
    - interfacer # deprecated
    - lll
    - maligned # deprecated
    - misspell
    - nlreturn
    - promlinter
    - scopelint # deprecated
    - varnamelen
```

I'm using

```
golangci-lint has version 1.44.0 built from 617470fa on 2022-01-25T11:31:17Z
```

What's the problem?
