### ISSUE TITLE
Getting error when golint is enabled

### ISSUE THREAD

**Issue by yunmanger1** [xxpxxxxp/intellij-plugin-golangci-lint#151]
I keep getting error if I enable golint in .golangci.yml

```
Please make sure no syntax or config error, then run 'go mod tidy' to ensure deps ok
```

and error goes away if I remove golint

```
linters:
  enable:
    - golint
  disable:
    - errcheck
    - staticcheck
    - ineffassign
    - govet
```
