### ISSUE TITLE
Go linter running error. Possibly invalid config or syntax error.

### ISSUE THREAD

**Issue by arvenil** [xxpxxxxp/intellij-plugin-golangci-lint#31]
The linter works from command line however when I try to set it up in IntelliJ it fails:
<img width="774" alt="image" src="https://user-images.githubusercontent.com/450355/89886235-95b99400-dbcc-11ea-8d52-9f50a7bba513.png">
But it is configured
<img width="758" alt="image" src="https://user-images.githubusercontent.com/450355/89886307-b41f8f80-dbcc-11ea-9496-6f20e1e33f2f.png">

How can I check what error it returns?

**Comment by xxpxxxxp** [comment]
Hi @arvenil , you can find log at
Help - Show Log in Finder
Then open `idea.log` with an editor, search for `go-linter`

There should be something like `Run error: ...`
Please paste the error here to help me troubleshooting.

**Comment by arvenil** [comment]
Thanks! Extracted from the log. Apparently it doesn't like enable-all option. It properly however picked up all linters to enable except three disabled.
```
go-linter - Run error: level=error msg="Running error: --enable-all and --disable-all options must not be combined"
golangci-lint run --out-format json --concurrency 3 --max-issues-per-linter 0 --max-same-issues 0 --maligned.suggest-new --disable-all -E
```
```
linters:
  enable-all: true
  disable:
    - gofumpt
    - gci
    - testpackage
linters-settings:
  goimports:
    local-prefixes: x/api
issues:
  # Without below godoc is not being checked.
  exclude-use-default: false
```
