### ISSUE TITLE
IDE freezing during editing

### ISSUE THREAD

**Issue by tarmo-randma** [xxpxxxxp/intellij-plugin-golangci-lint#38]
When editing non-go files (in my case *md files) the IDE keeps freezing after every few seconds briefly. At the time I see from task manager that under IntelliJ IDEA app some additional processes are executed.. go.exe and golangci-lint.exe. During this time the editor window remains unresponsive.

Disabling this plugin eliminates the freezing issue with md files

While this freezing also occurs when editing go files, the behavior seems somewhat less annoying as it seems to be less frequent and appears to take place at more rational moments - when I am changing tabs or navigating around with the mouse. Still disrupts coding at times.

Go version: go1.14.2 windows/amd64
Plugin version: Go Linter 1.4.4

IDEA version info:
IntelliJ IDEA 2020.1.2 (Ultimate Edition)
Build #IU-201.7846.76, built on June 1, 2020
Runtime version: 11.0.7+10-b765.53 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
Windows 10 10.0
GC: ParNew, ConcurrentMarkSweep
Memory: 1981M
Cores: 8
Registry: ide.intellij.laf.enable.animation=true, ide.balloon.shadow.size=0
Non-Bundled Plugins: Statistic, com.berzanmikaili.intellij.monokai_pro, com.fernandojimenez.mattecarbon.theme, com.fernandojimenez.obsidian.theme, mobi.hsz.idea.gitignore, Lombook Plugin, SBT, com.dubreuia, com.intellij.plugins.watcher, com.mallowigi.idea, com.markskelton.one-dark-theme, com.samdark.intellij-visual-studio-code-dark-plus, com.vermouthx.idea, io.eightpigs.intellij.darktheme, org.jetbrains.plugins.go, com.dmarcotte.handlebars, Dart, io.flutter, org.jetbrains.kotlin, org.intellij.scala, org.jetbrains.plugins.vue, com.jetbrains.php, org.psliwa.idea.composer, com.ypwang.plugin.go-linter

**Comment by xxpxxxxp** [comment]
@tarmo-randma Thanks for reporting!
For your first question, I'm suspecting your markdown file is associated with Go file type. If possible, would you mind install `PsiViewer` plugin from Intellij Marketplace, open the panel `View - Tool Windows - PsiViewer`, then open a markdown file in editor, check if the `containingFile` is `Markdown file` at top of the PsiViewer panel, like this:
![image](https://user-images.githubusercontent.com/1585918/94642795-cb9b0f00-0317-11eb-8780-4329c1ab6c7e.png)

For your second question, I'm working on improving the performance by moving most lints out of UI thread. Please hold tight and see if it's better at the next release in 2~3 weeks😁

**Comment by tarmo-randma** [comment]
After installing PsiViewer:
- for md file containingFile is "Markdown file"
- for go file containingFile is "GO_FILE"

When I restarted the IDE to make sure everything was fresh, I saw the same results in PsiViewer, but md files did not lag any more. Task manager also did not show "golangci-lint.exe" executing when editing md files.

This matches what I have seen earlier as well.. On a clean restart of the machine there are no stuttering issues.. but after working with the IDE for a while, it starts stuttering. I assumed fixing the stutter required a full machine restart but at least this time an IDE restart seemed to have been enough.

The reason I did not mention things working fine on a clean restart was that I had assumed the issue was with my machine resources running out. Now it would appear that something actually changes during the application use and the linter starts executing for files where it should not execute.

I will wait for the stutter to return and will report back what the PsiViewer shows at the time md files cause stuttering.

**Comment by tarmo-randma** [comment]
Markdown files started stuttering again. The lockups in go files also got worse at the same time. PsiViewer is still showing correct containingFile values.

The only additional lead maybe worth mentioning is that I am working with several project open in several IDE windows at the same time - so maybe these different windows cause issues? Maybe validation is triggered for all IDE instances or some other configuration cross projects messes things up?

Nothing else to report

**Comment by xxpxxxxp** [comment]
Thanks @tarmo-randma for infos, I'll try to identify the problem.

**Comment by xxpxxxxp** [comment]
Hi @tarmo-randma , please help me check if the new release fixes the problem, thanks.

**Comment by tarmo-randma** [comment]
1.4.5 is not available through the inteij updater. I tried also uninstalling and reinstalling the plugin but it still got just 1.4.4

**Comment by tarmo-randma** [comment]
In 1.4.5 the plugin is still causing stuttering in go files. Never got to the markdown files.. had to disable it as it was too noticable. It feels very much like that all work is still done in the UI thread

**Comment by iangregsondev** [comment]
Hi, I am also getting this. Using the latest version of the plugin.

Updated the golinter binary.

I was going crazy - I thought there was an issue with intellij. It was soooooo slow, code completion would just pause. It was unworkable.

I removed some flutter plugins as I wasn't using them - figured something like that might be causing an issue - but nothing - still the same..

Finally, I removed this plugin and everything is back to full speed.

I would really like to provide more info so we can investigate.

Can I provide any further information?

I miss the plugin :-)

**Comment by iangregsondev** [comment]
One thing I forgot to mention is that I did upgrade the linter via the command line as intellij informed me there was an update but it couldn't update it via the IDE because of a permission issue so I did it through brew

```
==> Upgrading 1 outdated package:
golangci/tap/golangci-lint 1.31.0 -> 1.32.1
==> Upgrading golangci/tap/golangci-lint 1.31.0 -> 1.32.1
```

**Comment by xxpxxxxp** [comment]
@iangregsondev sorry for causing the problem, could I have your intellij version? A few other infos might help too, like
how many CPU cores and total memory does your MacBook has?
how many instances of intellij is currently opening?
what's the memory usage of intellij (you can see that by right click intellij's right-down corner and check memory indicator)?

**Comment by iangregsondev** [comment]
@xxpxxxxp Sure, so I have 32MB, let me paste a image here, a picture is worth 1000 words as they say :-)

![image](https://user-images.githubusercontent.com/2370364/97809167-a4639480-1c6b-11eb-96b7-89e546293624.png)


Also, I notice I have lots of memory available and also the CPU is not overworked at all.

To give you more info, I will need to reinstall the plugin - back in 10 mins with some more info..

**Comment by iangregsondev** [comment]
I have 2 instances open of intellij but I am not doing anything with the other right now.

![image](https://user-images.githubusercontent.com/2370364/97809289-46837c80-1c6c-11eb-80c1-6070099dac6c.png)

and

![image](https://user-images.githubusercontent.com/2370364/97809300-57cc8900-1c6c-11eb-9b6c-66486c3598be.png)

**Comment by iangregsondev** [comment]
Ahhh ! @xxpxxxxp so when you asked me about instances, I closed 1 down and now it works ok

If I open up another instance it dies again :-)

The 2 apps I have open are both golang and both are very simple apps.

Close the other down and everything is responsive again.

Having 2 instances, checking the memory and they are using about the same.

**Comment by xxpxxxxp** [comment]
Thank you, that echoes @tarmo-randma 's word, apparently there's performance downgrade in multiple instances, possibly race conditions. I'll try to identify it soon.

**Comment by xxpxxxxp** [comment]
Still could not repro the bug, @iangregsondev are you using `.golangci.yml` config? Could you share your config file with me? I'm suspecting a specific config triggered the bug.

**Comment by iangregsondev** [comment]
I am not using anything like that, i have no config what so ever... BUT.. The other repo i have open in another instance fo intellij does have that !

Let me give you the repo

https://github.com/prometheus/node_exporter

and here is the config

```
linters:
  enable:
  - golint

issues:
  exclude-rules:
  - path: _test.go
    linters:
    - errcheck

linters-settings:
  errcheck:
    exclude: scripts/errcheck_excludes.txt
```

I have this repo open because I am trying to use it as an example of some software I am developing..

So I have node-exporter (see above) open in one instance of intellij and it has it's own config (see above) - I am using the master branch

and I have my own app open in another instance of intellij, it has no config and very very small.

Does that help ?

**Comment by iangregsondev** [comment]
@xxpxxxxp Also i would like to state that it is dormant, I am not doing anything with the intellij instance - its only open, my main dev is happening in my own app in another intellij instance...

My intellij instance is what suffers when I have the other open, if I close the other instance (node-exporter) down then my instance now runs smoothly..

Weird :-)

**Comment by xxpxxxxp** [comment]
I can see the IDE stuck when I opened a file, then back to normal after a few seconds. I'll fix this problem first.

**Comment by xxpxxxxp** [comment]
I think I found the bug, I'll make a release tomorrow, please help me verify if that fixes the issue.

**Comment by iangregsondev** [comment]
@xxpxxxxp Sure, I have the 2 projects here - so I can easy to test it for you - no worries.

Let me know.

**Comment by iangregsondev** [comment]
Hi @xxpxxxxp , I noticed you released the new plugin.

I have just updated it and I am trying to reproduce it and it seems to be fixed!

I am currently in another project right now so I am with go at the moment but I was able to produce it very easily before and now since the update, the slowness has gone.

I have multiple projects open and the same 2 projects as before.

So from me, it looks good.

Now sure if anybody else can confirm or had similar issues.

**Comment by xxpxxxxp** [comment]
Thanks a lot for confirming @iangregsondev !

**Comment by xxpxxxxp** [comment]
Fixed IDE freezing in case of multi projects. Feel free to reopen if the issue still happening.

**Comment by sudo-suhas** [comment]
I am facing this issue with the following:

```
$ go version
go version go1.15.8 darwin/amd64

$ bin/golangci-lint --version
golangci-lint has version 1.37.1 built from b39dbcd6 on 2021-02-20T11:48:06Z
```

Go linter version: 1.4.11
GoLand: 2020.3.2, VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
macOS 10.15.7
Non-Bundled Plugins: Key Promoter X, String Manipulation, com.intellij.properties, com.intellij.tasks, com.vecheslav.darculaDarkerTheme, io.protostuff.protostuff-jetbrains-plugin, mobi.hsz.idea.gitignore, com.jetbrains.codeWithMe, name.kropp.intellij.makefile, org.toml.lang, com.intellij.swagger, net.ashald.envfile

<details>
<summary><code>.golangci.toml</code></summary>

```toml
# Configuration for golangci-lint
# See https://golangci-lint.run/usage/configuration/#config-file

# See https://golangci-lint.run/usage/linters/
[linters]
  # Disable-all, coupled with enable, scales well with updates to golangci-lint
  disable-all = true

  enable = [
    # https://golang.org/cmd/vet/
    # Examines Go source code and reports suspicious constructs.
    "govet",

    # https://github.com/kisielk/errcheck
    # Checks for unchecked errors in go programs.
    "errcheck",

    # https://staticcheck.io/
    # Staticcheck is a go vet on steroids, applying a ton of static analysis checks.
    "staticcheck",

    # https://github.com/dominikh/go-tools/tree/master/unused
    # Checks Go code for unused constants, variables, functions and types.
    "unused",

    # https://github.com/dominikh/go-tools/tree/master/unused
    # Suggests simplifications for code.
    "gosimple",

    # https://github.com/gordonklaus/ineffassign
    # Detects when assignments to existing variables are not used.
    "ineffassign",

    # https://github.com/dominikh/go-tools/tree/master/stylecheck
    # Similar to and replacement for golint - prints out style mistakes.
    "stylecheck",

    # https://github.com/mdempsky/unconvert
    # Removes unnecessary type conversions.
    "unconvert",

    # https://github.com/mibk/dupl
    # Detects duplication in code blocks.
    "dupl",

    # https://github.com/jgautheron/goconst
    # Finds repeated strings that could be replaced by a constant.
    "goconst",

    # https://github.com/daixiang0/gci
    # Gci control golang package import order and make it always deterministic.
    "gci",

    # https://github.com/golang/lint
    # Golint differs from gofmt. Gofmt reformats Go source code, whereas golint prints out style mistakes
    "golint",

    # https://github.com/mvdan/gofumpt
    # Gofumpt checks whether code was gofumpt-ed.
    "gofumpt",

    # https://github.com/client9/misspell
    # Finds commonly misspelled English words in comments.
    "misspell",

    # https://github.com/alexkohler/nakedret
    # Finds naked returns in functions greater than a specified function length.
    "nakedret",

    # https://github.com/ashanbrown/forbidigo
    # Forbids identifiers
    "forbidigo",

    # https://github.com/go-critic/go-critic
    # The most opinionated Go source code linter
    "gocritic",

    # https://github.com/walle/lll
    # Reports long lines
    "lll",

    # https://github.com/mbilski/exhaustivestruct
    # Checks if all struct's fields are initialized
    "exhaustivestruct",
  ]

# Options for analysis running
[run]
  # Which dirs to skip: issues from them won't be reported;
  # can use regexp here: generated.*, regexp is applied on full path;
  # By default, directories such as `vendor/` are skipped independently from this
  # option's value.
  skip-dirs = [
    "bin",
    "migrations",
    "out",
    "swagger",
  ]

  skip-files = [
    ".*mock.*\\.go$"
  ]

  # golangci-lint passes it to "go list -mod={option}". From "go help modules":
  # If invoked with -mod=readonly, the go command is disallowed from the implicit
  # automatic updating of go.mod described above. Instead, it fails when any
  # changes to go.mod are needed. This setting is most useful to check that
  # go.mod does not need updates, such as in a continuous integration and testing
  # system. If invoked with -mod=vendor, the go command assumes that the vendor
  # directory holds the correct copies of dependencies and ignores the dependency
  # descriptions in go.mod.
  modules-download-mode = "readonly"

# All available settings of specific linters
[linters-settings]

  [linters-settings.govet]
    # Report about shadowed variables
    check-shadowing = true

    enable-all = true
    # Disable analyzers by name
    # See https://golang.org/cmd/vet/
    disable = [
      # (not needed) report mismatches between assembly files and Go declarations
      "asmdecl",
      # (dupl staticcheck) check for useless assignments
      "assign",
    ]

  [linters-settings.errcheck]
    # Report about not checking of errors in type assetions: `a := b.(MyStruct)`;
    # default is false: such cases aren't reported by default.
    check-type-assertions = true

  [linters-settings.goimports]
    # Put imports beginning with prefix after 3rd-party packages;
    # it's a comma-separated list of prefixes
    local-prefixes = "my.company.com"

  [linters-settings.misspell]
    # Correct spellings using locale preferences for US or UK.
    # Default is to use a neutral variety of English.
    # Setting locale to US will correct the British spelling of 'colour' to 'color'.
    locale = "US"
    ignore-words = [
      "cancelled"
    ]

  [linters-settings.gofumpt]
    # Choose whether or not to use the extra rules that are disabled
    # by default
    extra-rules = true

  [linters-settings.forbidigo]
    # Forbid the following identifiers
    forbid = [
      "fmt\\.Printf.*",
      "logger\\.Log.*\\(fmt\\.Sprintf.*",
    ]

  [linters-settings.gocritic]
    enabled-checks = [
      "argOrder", # Detects suspicious arguments order
      "badCall", # Detects suspicious function calls
      "badCond", # Detects suspicious condition expressions
      "commentedOutCode", # Detects commented-out code inside function bodies
      "deprecatedComment", # Detects malformed 'deprecated' doc-comments
      "dupArg", # Detects suspicious duplicated arguments
      "dupBranchBody", # Detects duplicated branch bodies inside conditional statements
      "dupCase", # Detects duplicated case clauses inside switch statements
      "dupSubExpr", # Detects suspicious duplicated sub-expressions
      "exitAfterDefer", # Detects calls to exit/fatal inside functions that use defer
      "mapKey", # Detects suspicious map literal keys
      "nilValReturn", # Detects return statements those results evaluate to nil
      "offBy1", # Detects various off-by-one kind of errors
      "sloppyReassign", # Detects suspicious/confusing re-assignments
      "truncateCmp", # Detects potential truncation issues when comparing ints of different sizes
      "weakCond", # Detects conditions that are unsafe due to not being exhaustive
      "assignOp", # Detects assignments that can be simplified by using assignment operators
      "boolExprSimplify", # Detects bool expressions that can be simplified
      "builtinShadow", # Detects when predeclared identifiers are shadowed in assignments
      "captLocal", # Detects capitalized names for local variables
      "commentedOutImport", # Detects commented-out imports
      "defaultCaseOrder", # Detects when default case in switch isn't on 1st or last position
      "elseif", # Detects else with nested if statement that can be replaced with else-if
      "emptyFallthrough", # Detects fallthrough that can be avoided by using multi case values
      "ifElseChain", # Detects repeated if-else statements and suggests to replace them with switch statement
      "regexpSimplify", # Detects regexp patterns that can be simplified
      "singleCaseSwitch", # Detects switch statements that could be better written as if statement
      "underef", # Detects dereference expressions that can be omitted
      "wrapperFunc", # Detects function calls that can be replaced with convenience wrappers
      "appendCombine", # Detects `append` chains to the same slice that can be done in a single `append` call
    ]

    # Settings passed to gocritic.
    # The settings key is the name of a supported gocritic checker.
    # The list of supported checkers can be find in https://go-critic.github.io/overview.
    [linters-settings.gocritic.settings]
      # whether to restrict checker to params only (default true)
      captLocal = { paramsOnly = false }

  [linters-settings.lll]
    # max line length, lines longer will be reported. Default is 120.
    # '\t' is counted as 1 character by default, and can be changed with the tab-width option
    line-length = 160
    # tab width in spaces. Default to 1.
    tab-width = 1

  [linters-settings.exhaustivestruct]
    # List of expressions to match struct packages and names
    # The struct packages have the form example.com/package.ExampleStruct.
    # The matching patterns can use matching syntax from https://pkg.go.dev/path#Match.
    struct-patterns = [
      "my.company.com/mygroup/myapp/*ServiceParams",
      "my.company.com/mygroup/myapp/*/*ServiceParams",
    ]

[issues]
  # List of regexps of issue texts to exclude, empty list by default.
  # But independently from this option we use default exclude patterns,
  # it can be disabled by `exclude-use-default: false`. To list all
  # excluded by default patterns execute `golangci-lint run --help`
  exclude=[
    'declaration of "(err|ctx)" shadows declaration at',
  ]

  # Excluding configuration per-path, per-linter, per-text and per-source
  [[issues.exclude-rules]]
    # Exclude some linters from running on tests files.
    path = "_test\\.go"
    linters = [
      "dupl",
      "gosec",
      "lll",
    ]

  [[issues.exclude-rules]]
    path = "_test\\.go"
    text = "^Error return value is not checked$"
    linters = ["errcheck"]

```

</details>

I am also seeing errors in the event log:
<img width="681" alt="image" src="https://user-images.githubusercontent.com/22251956/108618026-ac288e00-7440-11eb-9e10-61533923102c.png">

There are no syntax errors in the project being checked so not sure what is the issue here.
