### ISSUE TITLE
Plugin does not seem to recognize exclude-rules for gomnd

### ISSUE THREAD

**Issue by pauloavelar** [xxpxxxxp/intellij-plugin-golangci-lint#41]
I am not sure if this is related to how `golangci-lint` is called by the plugin or something specific to **gomnd**, but it is flagging magic numbers for files excluded in `issues.exclude-rules`.

When golangci-lint is called from the terminal, no issues are listed.

Exclusions:
```yaml
issues:
  exclude-use-default: true
  max-issues-per-linter: 0
  max-same-issues: 0
  new: false
  exclude-rules:
    - path: testutils
      linters:
        - gomnd
```

Screenshots:
![image](https://user-images.githubusercontent.com/1754076/98446655-c478d500-20fd-11eb-9740-c2c91f9a2902.png)
