### ISSUE TITLE
Can't pass in --fix or --fast flags

### ISSUE THREAD

**Issue by mattayes** [xxpxxxxp/intellij-plugin-golangci-lint#47]
In Goland 2020.2 I could pass in custom flags to `golangci-lint`. I would pass `--fix` to autofix issues and `--fast` to skip slow linters. In 2020.3 that option is no longer available, making some linters (e.g., `gci`) painful to use.

Is there a way to specify these flags?

**Comment by xxpxxxxp** [comment]
Hi @mattayes , `custom option` is removed as nearly all options could be set via configuration file, refer to https://golangci-lint.run/usage/configuration/

For your needs, I think `.golangci.yml` below should work:
```
linters:
  enable:
    - megacheck
    - govet
  disable:
    - maligned
    - prealloc
  disable-all: false
  fast: true
issues:
  fix: true
```

But be noted to add your desired linters to `enable` section, if config file is used, linters set in plugin panel will be ignored.
