### ISSUE TITLE
I am facing this issue with the following:

### ISSUE THREAD

**Issue by xxpxxxxp** [xxpxxxxp/intellij-plugin-golangci-lint#62]
I am facing this issue with the following:

```
$ go version
go version go1.15.8 darwin/amd64

$ bin/golangci-lint --version
golangci-lint has version 1.37.1 built from b39dbcd6 on 2021-02-20T11:48:06Z
```

Go linter version: 1.4.11
GoLand: 2020.3.2, VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
macOS 10.15.7
Non-Bundled Plugins: Key Promoter X, String Manipulation, com.intellij.properties, com.intellij.tasks, com.vecheslav.darculaDarkerTheme, io.protostuff.protostuff-jetbrains-plugin, mobi.hsz.idea.gitignore, com.jetbrains.codeWithMe, name.kropp.intellij.makefile, org.toml.lang, com.intellij.swagger, net.ashald.envfile

<details>
<summary><code>.golangci.toml</code></summary>

```toml
# Configuration for golangci-lint
# See https://golangci-lint.run/usage/configuration/#config-file

# See https://golangci-lint.run/usage/linters/
[linters]
  # Disable-all, coupled with enable, scales well with updates to golangci-lint
  disable-all = true

  enable = [
    # https://golang.org/cmd/vet/
    # Examines Go source code and reports suspicious constructs.
    "govet",

    # https://github.com/kisielk/errcheck
    # Checks for unchecked errors in go programs.
    "errcheck",

    # https://staticcheck.io/
    # Staticcheck is a go vet on steroids, applying a ton of static analysis checks.
    "staticcheck",

    # https://github.com/dominikh/go-tools/tree/master/unused
    # Checks Go code for unused constants, variables, functions and types.
    "unused",

    # https://github.com/dominikh/go-tools/tree/master/unused
    # Suggests simplifications for code.
    "gosimple",

    # https://github.com/gordonklaus/ineffassign
    # Detects when assignments to existing variables are not used.
    "ineffassign",

    # https://github.com/dominikh/go-tools/tree/master/stylecheck
    # Similar to and replacement for golint - prints out style mistakes.
    "stylecheck",

    # https://github.com/mdempsky/unconvert
    # Removes unnecessary type conversions.
    "unconvert",

    # https://github.com/mibk/dupl
    # Detects duplication in code blocks.
    "dupl",

    # https://github.com/jgautheron/goconst
    # Finds repeated strings that could be replaced by a constant.
    "goconst",

    # https://github.com/daixiang0/gci
    # Gci control golang package import order and make it always deterministic.
    "gci",

    # https://github.com/golang/lint
    # Golint differs from gofmt. Gofmt reformats Go source code, whereas golint prints out style mistakes
    "golint",

    # https://github.com/mvdan/gofumpt
    # Gofumpt checks whether code was gofumpt-ed.
    "gofumpt",

    # https://github.com/client9/misspell
    # Finds commonly misspelled English words in comments.
    "misspell",

    # https://github.com/alexkohler/nakedret
    # Finds naked returns in functions greater than a specified function length.
    "nakedret",

    # https://github.com/ashanbrown/forbidigo
    # Forbids identifiers
    "forbidigo",

    # https://github.com/go-critic/go-critic
    # The most opinionated Go source code linter
    "gocritic",

    # https://github.com/walle/lll
    # Reports long lines
    "lll",

    # https://github.com/mbilski/exhaustivestruct
    # Checks if all struct's fields are initialized
    "exhaustivestruct",
  ]

# Options for analysis running
[run]
  # Which dirs to skip: issues from them won't be reported;
  # can use regexp here: generated.*, regexp is applied on full path;
  # By default, directories such as `vendor/` are skipped independently from this
  # option's value.
  skip-dirs = [
    "bin",
    "migrations",
    "out",
    "swagger",
  ]

  skip-files = [
    ".*mock.*\\.go$"
  ]

  # golangci-lint passes it to "go list -mod={option}". From "go help modules":
  # If invoked with -mod=readonly, the go command is disallowed from the implicit
  # automatic updating of go.mod described above. Instead, it fails when any
  # changes to go.mod are needed. This setting is most useful to check that
  # go.mod does not need updates, such as in a continuous integration and testing
  # system. If invoked with -mod=vendor, the go command assumes that the vendor
  # directory holds the correct copies of dependencies and ignores the dependency
  # descriptions in go.mod.
  modules-download-mode = "readonly"

# All available settings of specific linters
[linters-settings]

  [linters-settings.govet]
    # Report about shadowed variables
    check-shadowing = true

    enable-all = true
    # Disable analyzers by name
    # See https://golang.org/cmd/vet/
    disable = [
      # (not needed) report mismatches between assembly files and Go declarations
      "asmdecl",
      # (dupl staticcheck) check for useless assignments
      "assign",
    ]

  [linters-settings.errcheck]
    # Report about not checking of errors in type assetions: `a := b.(MyStruct)`;
    # default is false: such cases aren't reported by default.
    check-type-assertions = true

  [linters-settings.goimports]
    # Put imports beginning with prefix after 3rd-party packages;
    # it's a comma-separated list of prefixes
    local-prefixes = "my.company.com"

  [linters-settings.misspell]
    # Correct spellings using locale preferences for US or UK.
    # Default is to use a neutral variety of English.
    # Setting locale to US will correct the British spelling of 'colour' to 'color'.
    locale = "US"
    ignore-words = [
      "cancelled"
    ]

  [linters-settings.gofumpt]
    # Choose whether or not to use the extra rules that are disabled
    # by default
    extra-rules = true

  [linters-settings.forbidigo]
    # Forbid the following identifiers
    forbid = [
      "fmt\\.Printf.*",
      "logger\\.Log.*\\(fmt\\.Sprintf.*",
    ]

  [linters-settings.gocritic]
    enabled-checks = [
      "argOrder", # Detects suspicious arguments order
      "badCall", # Detects suspicious function calls
      "badCond", # Detects suspicious condition expressions
      "commentedOutCode", # Detects commented-out code inside function bodies
      "deprecatedComment", # Detects malformed 'deprecated' doc-comments
      "dupArg", # Detects suspicious duplicated arguments
      "dupBranchBody", # Detects duplicated branch bodies inside conditional statements
      "dupCase", # Detects duplicated case clauses inside switch statements
      "dupSubExpr", # Detects suspicious duplicated sub-expressions
      "exitAfterDefer", # Detects calls to exit/fatal inside functions that use defer
      "mapKey", # Detects suspicious map literal keys
      "nilValReturn", # Detects return statements those results evaluate to nil
      "offBy1", # Detects various off-by-one kind of errors
      "sloppyReassign", # Detects suspicious/confusing re-assignments
      "truncateCmp", # Detects potential truncation issues when comparing ints of different sizes
      "weakCond", # Detects conditions that are unsafe due to not being exhaustive
      "assignOp", # Detects assignments that can be simplified by using assignment operators
      "boolExprSimplify", # Detects bool expressions that can be simplified
      "builtinShadow", # Detects when predeclared identifiers are shadowed in assignments
      "captLocal", # Detects capitalized names for local variables
      "commentedOutImport", # Detects commented-out imports
      "defaultCaseOrder", # Detects when default case in switch isn't on 1st or last position
      "elseif", # Detects else with nested if statement that can be replaced with else-if
      "emptyFallthrough", # Detects fallthrough that can be avoided by using multi case values
      "ifElseChain", # Detects repeated if-else statements and suggests to replace them with switch statement
      "regexpSimplify", # Detects regexp patterns that can be simplified
      "singleCaseSwitch", # Detects switch statements that could be better written as if statement
      "underef", # Detects dereference expressions that can be omitted
      "wrapperFunc", # Detects function calls that can be replaced with convenience wrappers
      "appendCombine", # Detects `append` chains to the same slice that can be done in a single `append` call
    ]

    # Settings passed to gocritic.
    # The settings key is the name of a supported gocritic checker.
    # The list of supported checkers can be find in https://go-critic.github.io/overview.
    [linters-settings.gocritic.settings]
      # whether to restrict checker to params only (default true)
      captLocal = { paramsOnly = false }

  [linters-settings.lll]
    # max line length, lines longer will be reported. Default is 120.
    # '\t' is counted as 1 character by default, and can be changed with the tab-width option
    line-length = 160
    # tab width in spaces. Default to 1.
    tab-width = 1

  [linters-settings.exhaustivestruct]
    # List of expressions to match struct packages and names
    # The struct packages have the form example.com/package.ExampleStruct.
    # The matching patterns can use matching syntax from https://pkg.go.dev/path#Match.
    struct-patterns = [
      "my.company.com/mygroup/myapp/*ServiceParams",
      "my.company.com/mygroup/myapp/*/*ServiceParams",
    ]

[issues]
  # List of regexps of issue texts to exclude, empty list by default.
  # But independently from this option we use default exclude patterns,
  # it can be disabled by `exclude-use-default: false`. To list all
  # excluded by default patterns execute `golangci-lint run --help`
  exclude=[
    'declaration of "(err|ctx)" shadows declaration at',
  ]

  # Excluding configuration per-path, per-linter, per-text and per-source
  [[issues.exclude-rules]]
    # Exclude some linters from running on tests files.
    path = "_test\\.go"
    linters = [
      "dupl",
      "gosec",
      "lll",
    ]

  [[issues.exclude-rules]]
    path = "_test\\.go"
    text = "^Error return value is not checked$"
    linters = ["errcheck"]

```

</details>

I am also seeing errors in the event log:
<img width="681" alt="image" src="https://user-images.githubusercontent.com/22251956/108618026-ac288e00-7440-11eb-9e10-61533923102c.png">

There are no syntax errors in the project being checked so not sure what is the issue here.

_Originally posted by @sudo-suhas in https://github.com/xxpxxxxp/intellij-plugin-golangci-lint/issues/38#issuecomment-782812256_
